name: uber_like_maps_with_google_maps_platform
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: packages/api_client
  core:
    path: packages/core
  google_maps_flutter: ^2.6.0
  flutter_bloc: ^8.1.4
  geolocator: ^11.0.0
  bloc_concurrency: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
